name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Get built project
        uses: actions/download-artifact@v4
        with:
          name: build-files