name: Deploy Ract App
on: push
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Lint application
        run: npm run lint
      - name: Deploy
        run: echo deploying...